"""Revert to original models

Revision ID: 37b4198afc00
Revises: 68599b2e7355
Create Date: 2024-11-17 09:47:19.819293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b4198afc00'
down_revision = '68599b2e7355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_professor_id', sa.INTEGER(), nullable=False),
    sa.Column('reviewer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_professor_id'], ['course_professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
