"""added models

Revision ID: d7a5046c6785
Revises: e2fe6c12dd97
Create Date: 2024-11-16 21:25:20.847127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a5046c6785'
down_revision = 'e2fe6c12dd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_preferences', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('class_time_preferences', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('class_time_preferences')
        batch_op.drop_column('assignment_preferences')

    # ### end Alembic commands ###
